//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.02 at 01:07:53 PM GMT+03:00 
//


package ru.qweert.martha;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for goodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="goodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ВЫЧИСЛИТЕЛЬНАЯ ТЕХНИКА"/>
 *     &lt;enumeration value="БЫТОВАЯ ТЕХНИКА"/>
 *     &lt;enumeration value="КОМПЬЮТЕРНАЯ ПЕРИФЕРИЯ"/>
 *     &lt;enumeration value="БЫТОВАЯ ХИМИЯ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "goodType")
@XmlEnum
public enum GoodType {

    @XmlEnumValue("\u0412\u042b\u0427\u0418\u0421\u041b\u0418\u0422\u0415\u041b\u042c\u041d\u0410\u042f \u0422\u0415\u0425\u041d\u0418\u041a\u0410")
    ВЫЧИСЛИТЕЛЬНАЯ_ТЕХНИКА("\u0412\u042b\u0427\u0418\u0421\u041b\u0418\u0422\u0415\u041b\u042c\u041d\u0410\u042f \u0422\u0415\u0425\u041d\u0418\u041a\u0410"),
    @XmlEnumValue("\u0411\u042b\u0422\u041e\u0412\u0410\u042f \u0422\u0415\u0425\u041d\u0418\u041a\u0410")
    БЫТОВАЯ_ТЕХНИКА("\u0411\u042b\u0422\u041e\u0412\u0410\u042f \u0422\u0415\u0425\u041d\u0418\u041a\u0410"),
    @XmlEnumValue("\u041a\u041e\u041c\u041f\u042c\u042e\u0422\u0415\u0420\u041d\u0410\u042f \u041f\u0415\u0420\u0418\u0424\u0415\u0420\u0418\u042f")
    КОМПЬЮТЕРНАЯ_ПЕРИФЕРИЯ("\u041a\u041e\u041c\u041f\u042c\u042e\u0422\u0415\u0420\u041d\u0410\u042f \u041f\u0415\u0420\u0418\u0424\u0415\u0420\u0418\u042f"),
    @XmlEnumValue("\u0411\u042b\u0422\u041e\u0412\u0410\u042f \u0425\u0418\u041c\u0418\u042f")
    БЫТОВАЯ_ХИМИЯ("\u0411\u042b\u0422\u041e\u0412\u0410\u042f \u0425\u0418\u041c\u0418\u042f");
    private final String value;

    GoodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GoodType fromValue(String v) {
        for (GoodType c: GoodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
